### ISSUE TITLE
Stopped working after HA 2022.11.2 update

### ISSUE THREAD

**Issue by ModuCZ** [kvj/hass_nuki_ng#116]
Hi kvj,
after update to HA 2022.11.2 there’s probably issue with nuki_card_callback.

YAML Configuration check responds with configuration invalid.
ERR: Package nuki_card_callback setup failed. Component rest cannot be merged. Expected a dict.

Home Assistant 2022.11.2 (Docker container)
Frontend 20221108.0 - latest
Nuki Card Callback v11

**Comment by carsaig** [comment]
Same here. Same system state as above.

**Comment by ZeroKing666** [comment]
Same here and same system

**Comment by kvj** [comment]
hi everyone,
this repo has nothing to do with the nuki_card.
@alexdelprete do you know what's causing this error above?

**Comment by ModuCZ** [comment]
Solved this issue by migrating from Nuki Card to Nuki NG. I just missed info that Nuki Card is superseded. Sorry for confusion.

**Comment by alexdelprete** [comment]
> @alexdelprete do you know what's causing this error above?

probably the fact they didn't read the first post in the Nuki Card thread, where I recommend to install Nuki NG. :)

**Comment by TurboKanne** [comment]
Hi, since the update on 2022.12 my Nuki Lock does not work. I tried to reconfigure by deleting the Nuki NG integration, removing the Hacs part. Then re-installing the Hacs part, rebooting HA, and then while configureing Nuki NG Lock with the Web-Token and/or the Bridge Token, it always says, that there was a communication issue between HA and Nuki Bridge. So it does not work at all anymore. Is there something that can be done?

best regards

currently I am running 2022.12.5 on a RPI 3.
