### ISSUE TITLE
Nuki Bridge Bridge Callback is Disconnected

### ISSUE THREAD

**Issue by roeidalm** [kvj/hass_nuki_ng#4]
Hi,
I try to connect to a Callback function. But there aren't docs or explain why this is not working.
Would you please explain to me how to do this?

**Comment by kvj** [comment]
Not sure I understand the issue. What kind of error are you getting?

**Comment by roeidalm** [comment]
There is any guide how to connect the nuki to callback?

**Comment by kvj** [comment]
You don't need to do anything in order to set a callback. The integration will do it for you. 

Just make sure you set a correct Home assistant internal URL, using `http://` schema. The callback status is being reported via the `Bridge Callback Set` sensor

**Comment by roeidalm** [comment]
OK,
so it's not working, how can I send you the debug or the data?

**Comment by roeidalm** [comment]
Logger: custom_components.nuki_ng.nuki
Source: custom_components/nuki_ng/nuki.py:117
Integration: Nuki Lock (documentation, issues)
First occurred: 9:42:57 PM (7 occurrences)
Last logged: 9:46:00 PM
Failed to update callback http://192.168.2.135:8123/api/webhook/nuki_ng_bridge_hook_59156d185971e941.......

Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/nuki.py", line 201, in _update
    await self.api.bridge_check_callback(self.bridge_hook)
  File "/config/custom_components/nuki_ng/nuki.py", line 117, in bridge_check_callback
    raise ConnectionError(result.get("message"))
ConnectionError: too many callbacks registered

**Comment by kvj** [comment]
As per the error, `ConnectionError: too many callbacks registered`, the component isn't able to register another callback, because Nuki Bridge supports max 3 different callbacks.

You have multiple options to resolve that:
1. (Make sure you're using the latest version) Remove other callback(s) by calling custom service `nuki_ng.bridge_delete_callback`. The list of callbacks currently set is available as custom attributes of the entity above

<img width="416" alt="Screenshot 2021-11-14 at 20 58 23" src="https://user-images.githubusercontent.com/159124/141696483-160413f4-192a-48da-aaea-1cada54bfe83.png">

2. Remove other callback(s) manually, via API call https://developer.nuki.io/page/nuki-bridge-http-api-1-12/4#heading--callback-remove
3. Reset your bridge to have all callbacks removed

**Comment by roeidalm** [comment]
You are amazing! thanks! this fix that!
