### ISSUE TITLE
Callback not working (only polling)

### ISSUE THREAD

**Issue by hnykda** [kvj/hass_nuki_ng#42]
Hi,

my understanding was that the mentioned callback should update the sensors states (e.g. `door state` sensor) immediately after the door is open/closed. 

Unfortunately, even though the callback is listed in callbacks and the state is updated via polling (e.g. if I keep the door open for >30 secs - the default polling interval - the door state sensor is changed), the update isn't immediate (which is what I would like to achieve).

Is there a way how to get "immediate" updates of sensors?

**Comment by alexdelprete** [comment]
All users have immediate updates, when the callback is working. Your problem is that it isn't working, but if you don't provide info we can't try to help you. Check logs for errors, and make sure HA is not hardened via SSL on local network: the bridge can't call an https url, it's a limitation of the bridge.

**Comment by hnykda** [comment]
Got it, sorry, I just wasn't sure. Thanks for a quick response! I am not using HTTPS/SSL and the address in the callback looks correct. What info would you please need?

This is what the callback shows.
![image](https://user-images.githubusercontent.com/2741256/154849953-eb734ab6-c599-428a-8a36-f5f50270f008.png)

**Comment by hnykda** [comment]
I removed the additional callback the result is still the same. Nothing is logged in Core logs.

**Comment by hnykda** [comment]
Ha, now looking at the callback, it doesn't have the right port in it :facepalm:

**Comment by hnykda** [comment]
OK, that was it. Apologies. But I would propose mentioning this in the README - I used the default "discovered" default values when adding the integration and the IP was correct, but the port wasn't there. Thank you a lot for helping!

**Comment by alexdelprete** [comment]
> Ha, now looking at the callback, it doesn't have the right port in it 🤦

The callback has 8123, it was autodetected but it was wrong? Strange...are you using a proxy or something?

**Comment by hnykda** [comment]
The first callback was wrong, that was from old Nuki card. The second one was the one added by this integration and that one has `:8123` missing at the end of the IP. When I added `:8123` to the `Homeassistant URL` when setting up the integration, I got it working.

**Comment by alexdelprete** [comment]
In the post above, where you posted the screenshot, I see 8123, but in that post you say it's not working...

**Comment by hnykda** [comment]
The `callback#0` has it in, but that's some very old callback IP that is wrong (it has 8123 in it, but the IP is wrong). The second one has correct IP (192.168.0.202) but it's missing the port.

**Comment by alexdelprete** [comment]
The callback list has to have 1 entry, the one configured by the component. And it has to have the correct ip/port. That's the basic thing to check when debugging callback issues. If you notice multiple entries, there's a problem...

**Comment by hnykda** [comment]
Agree, that would likely make it much safer. At least mentioning it in Readme could be probably a good idea.

**Comment by alexdelprete** [comment]
Well...the root cause of the problem is almost always the fact that users don't check the configuration before submitting. You didn't notice that the port was missing, otherwise it would've worked since the beginning. Autodetection is a feature to help, but you always need to double-check what is detected. BTW: the fact that it detected the url without the port is really strange...did you configure internal_url and external_url in HA config?

Having said that, config control would be a wise thing to have less issues here. :)

**Comment by hnykda** [comment]
> did you configure internal_url and external_url in HA config?

You are right - I did configured that there and _without_ the port. So that was it. Thanks for your help and great work :bow:

**Comment by alexdelprete** [comment]
Thanks for confirming this.
